name: Build and Push to Docker Hub + GHCR

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write  # required for pushing to GHCR
      contents: write  # required for creating GitHub Releases

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # fetch all history and tags so we can compute changelog

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Login to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # Login to GitHub Container Registry (GHCR)
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Extract tag version
      id: extract_tag
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    ### FRONTEND IMAGE ###
    - name: Build & Push Frontend Image (Docker Hub + GHCR)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        build-args: |
          VERSION=${{ steps.extract_tag.outputs.VERSION }}
        tags: |
          timlohrer/auth-rs-frontend:${{ steps.extract_tag.outputs.VERSION }}
          timlohrer/auth-rs-frontend:latest
          ghcr.io/timlohrer/auth-rs-frontend:${{ steps.extract_tag.outputs.VERSION }}
          ghcr.io/timlohrer/auth-rs-frontend:latest
        labels: |
          org.opencontainers.image.source=https://github.com/timlohrer/auth-rs

    ### BACKEND IMAGE ###
    - name: Build & Push Backend Image (Docker Hub + GHCR)
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        build-args: |
          VERSION=${{ steps.extract_tag.outputs.VERSION }}
        tags: |
          timlohrer/auth-rs-backend:${{ steps.extract_tag.outputs.VERSION }}
          timlohrer/auth-rs-backend:latest
          ghcr.io/timlohrer/auth-rs-backend:${{ steps.extract_tag.outputs.VERSION }}
          ghcr.io/timlohrer/auth-rs-backend:latest
        labels: |
          org.opencontainers.image.source=https://github.com/timlohrer/auth-rs

    - name: Generate changelog
      id: changelog
      run: |
        git fetch --tags
        VERSION=${{ steps.extract_tag.outputs.VERSION }}
        # Find the previous tag (by creation date). If none exists, use initial commit range.
        PREV_TAG=$(git tag --sort=-creatordate | sed -n '2p' || true)

        if [ -n "$PREV_TAG" ]; then
          echo "Generating changelog from $PREV_TAG to $VERSION"
          CHANGES=$(git log --pretty=format:'- %s (%h)' $PREV_TAG..HEAD)
        else
          echo "No previous tag found, listing recent commits"
          CHANGES=$(git log --pretty=format:'- %s (%h)' -n 50)
        fi

        # Write multiline output to GITHUB_OUTPUT
        echo "changes<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGES" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.extract_tag.outputs.VERSION }}
        release_name: ${{ steps.extract_tag.outputs.VERSION }}
        body: ${{ steps.changelog.outputs.changes }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
